name: exservice
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  shimmer: ^2.0.0
  fluttertoast: ^8.0.9
  geolocator: ^8.2.1
  app_settings: ^4.1.6
  flutter_swiper: ^1.1.6
  chewie: ^1.3.3
  visibility_detector: ^0.2.2
  video_player: ^2.4.2
  expandable: ^5.0.1
  google_maps_flutter: ^2.1.5
  octo_image: ^1.0.2
  dashed_container: ^1.0.1
  pull_to_refresh: ^2.0.0
  permission_handler: ^9.2.0
  carousel_pro: any
  flutter_svg: ^1.0.3
  image_picker: ^0.8.5+3
  string_validator: ^0.3.0
  url_launcher: ^6.1.2
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^9.5.3+1
  cloud_firestore: ^3.1.16
  firebase_core: ^1.17.0
  bubble: ^1.2.1
  outline_gradient_button: ^2.0.0+1
  percent_indicator: ^4.0.0
  flutter_ffmpeg: ^0.4.2
  path_provider: ^2.0.10
  dio: ^4.0.6
  numberpicker: ^2.1.1
  webview_flutter: ^3.0.4
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  sliver_tools: ^0.2.6
  intl: ^0.17.0
  badges: ^2.0.2
  multi_select_flutter: ^4.1.2
  photo_manager: ^2.1.1
  simple_animated_icon: ^1.1.0
  readmore: ^2.1.0
  mask_text_input_formatter: ^2.3.0
  phone_number: ^0.12.0+2
  package_info_plus: ^1.4.0
  lottie: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lang/
  fonts:
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#565656"
  image: assets/images/app_icon.png
  image_dark: assets/images/app_icon.png